module.exports = {
  verbose: true,
  testEnvironment: 'jsdom',
  testEnvironmentOptions: {},
  maxWorkers: '50%',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  transform: {
    '^.+\\.(ts|tsx|js|jsx)$': '@swc/jest',
  },
  setupFiles: ['<rootDir>/jest-setup.ts'],
  setupFilesAfterEnv: ['@testing-library/jest-dom'],
  moduleNameMapper: {
    '^@fexd/mobile$': '<rootDir>/packages/mobile/src/index.ts',
  },
  testPathIgnorePatterns: [
    '/node_modules/',
    'packages/mobile/scripts/__tests__/',
    '\\.references/',
  ],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'text-summary', 'lcov', 'json-summary'],
  collectCoverageFrom: [
    'packages/mobile/src/exports/*/index.{ts,tsx}',
    '!packages/mobile/src/exports/*/tests/**',
    '!packages/mobile/src/exports/Breadcrumb/**',
    '!packages/mobile/src/exports/Calendar/**',
    '!packages/mobile/src/exports/Card/**',
    '!packages/mobile/src/exports/CountTo/**',
    '!packages/mobile/src/exports/Drag/**',
    '!packages/mobile/src/exports/Drawer/**',
    '!packages/mobile/src/exports/Dropdown/**',
    '!packages/mobile/src/exports/Elevator/**',
    '!packages/mobile/src/exports/Footer/**',
    '!packages/mobile/src/exports/Gallery/**',
    '!packages/mobile/src/exports/ImagePicker/**',
    '!packages/mobile/src/exports/List/**',
    '!packages/mobile/src/exports/Marquee/**',
    '!packages/mobile/src/exports/Menu/**',
    '!packages/mobile/src/exports/NumberKeyboard/**',
    '!packages/mobile/src/exports/Pagination/**',
    '!packages/mobile/src/exports/Search/**',
    '!packages/mobile/src/exports/SegmentedControl/**',
    '!packages/mobile/src/exports/ShareSheet/**',
    '!packages/mobile/src/exports/Sticky/**',
    '!packages/mobile/src/exports/SwipeAction/**',
    '!packages/mobile/src/exports/Table/**',
    '!packages/mobile/src/exports/Tips/**',
    '!packages/mobile/src/exports/TreeSelect/**',
    '!packages/mobile/src/exports/Video/**',
    '!packages/mobile/src/exports/Waterfall/**',
  ],
}
